spring.application.name=GroupProject

# ============================================================
# Database - MySQL (talenthub schema)
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5433/talenthub_schema
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# Thymeleaf
# ============================================================
spring.thymeleaf.cache=false

# ============================================================
# Server
# ============================================================
server.port=10111
server.error.whitelabel.enabled=false
